import { Escort } from '@/types/escorts'

export const mockEscorts: Escort[] = [
  {
    id: '1',
    name: 'Sophia',
    age: 25,
    description: 'Profissional elegante e discreta, especializada em acompanhamento de eventos sociais e viagens. Experiência em proporcionar momentos sofisticados e memoráveis. Também ofereço aluguel por temporada do meu espaço exclusivo, localizado em uma das melhores áreas de São Paulo. O espaço é totalmente mobiliado, com todas as comodidades necessárias para uma estadia confortável e luxuosa.',
    location: {
      city: 'São Paulo',
      state: 'SP',
      neighborhood: 'Jardins',
    },
    photos: [
      'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=800&q=80',
      'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=800&q=80',
      'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=800&q=80',
      'https://images.unsplash.com/photo-1611892440504-42a792e24d32?w=800&q=80',
      'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800&q=80',
    ],
    services: ['Eventos Sociais', 'Viagens', 'Jantares', 'Acompanhamento'],
    pricing: {
      hour: 500,
      night: 2000,
      weekend: 5000,
    },
    physicalAttributes: {
      height: '1.70m',
      bodyType: 'Esbelta',
      hairColor: 'Loiro',
      eyeColor: 'Verde',
    },
    rating: 4.9,
    reviewCount: 45,
    verified: true,
    premium: true,
    available: true,
    languages: ['Português', 'Inglês', 'Espanhol'],
    // Aluguel por temporada
    rentalAvailable: true,
    rentalPricing: {
      perNight: 350,
      perWeek: 2100,
      perMonth: 8000,
    },
    rentalAmenities: ['WiFi', 'Ar Condicionado', 'TV', 'Cofre', 'Frigobar', 'Varanda', 'Estacionamento'],
    rentalRules: ['Não fumar', 'Respeitar o espaço', 'Check-in após 15h', 'Check-out até 11h', 'Não animais'],
  },
  {
    id: '2',
    name: 'Isabella',
    age: 28,
    description: 'Companheira sofisticada para ocasiões especiais. Profissional, discreta e com excelente educação.',
    location: {
      city: 'Rio de Janeiro',
      state: 'RJ',
      neighborhood: 'Ipanema',
    },
    photos: [
      'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=800&q=80',
      'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=800&q=80',
    ],
    services: ['Eventos', 'Acompanhamento', 'Jantares'],
    pricing: {
      hour: 450,
      night: 1800,
    },
    physicalAttributes: {
      height: '1.65m',
      bodyType: 'Atlética',
      hairColor: 'Castanho',
    },
    rating: 4.7,
    reviewCount: 32,
    verified: true,
    premium: false,
    available: true,
    languages: ['Português', 'Inglês'],
  },
  {
    id: '3',
    name: 'Valentina',
    age: 23,
    description: 'Jovem, elegante e versátil. Perfeita para eventos corporativos e sociais.',
    location: {
      city: 'Belo Horizonte',
      state: 'MG',
      neighborhood: 'Savassi',
    },
    photos: [
      'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=800&q=80',
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&q=80',
    ],
    services: ['Eventos Corporativos', 'Acompanhamento', 'Viagens'],
    pricing: {
      hour: 400,
      night: 1500,
    },
    physicalAttributes: {
      height: '1.68m',
      bodyType: 'Esbelta',
      hairColor: 'Preto',
    },
    rating: 4.8,
    reviewCount: 28,
    verified: false,
    premium: false,
    available: true,
    languages: ['Português'],
  },
  {
    id: '4',
    name: 'Camila',
    age: 26,
    description: 'Elegante e profissional, especializada em eventos de alto padrão.',
    location: {
      city: 'São Paulo',
      state: 'SP',
      neighborhood: 'Vila Madalena',
    },
    photos: [
      'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=800&q=80',
      'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=800&q=80',
    ],
    services: ['Eventos', 'Acompanhamento', 'Viagens'],
    pricing: {
      hour: 480,
      night: 1900,
    },
    physicalAttributes: {
      height: '1.72m',
      bodyType: 'Esbelta',
      hairColor: 'Castanho',
    },
    rating: 4.6,
    reviewCount: 24,
    verified: true,
    premium: false,
    available: true,
    languages: ['Português', 'Inglês'],
  },
  {
    id: '5',
    name: 'Larissa',
    age: 24,
    description: 'Jovem e dinâmica, perfeita para eventos descontraídos e viagens.',
    location: {
      city: 'Brasília',
      state: 'DF',
      neighborhood: 'Asa Sul',
    },
    photos: [
      'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=800&q=80',
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&q=80',
    ],
    services: ['Eventos', 'Viagens', 'Acompanhamento'],
    pricing: {
      hour: 420,
      night: 1600,
    },
    physicalAttributes: {
      height: '1.66m',
      bodyType: 'Atlética',
      hairColor: 'Loiro',
    },
    rating: 4.7,
    reviewCount: 19,
    verified: false,
    premium: false,
    available: true,
    languages: ['Português'],
  },
  {
    id: '6',
    name: 'Fernanda',
    age: 29,
    description: 'Sofisticada e discreta, ideal para ocasiões formais e corporativas.',
    location: {
      city: 'São Paulo',
      state: 'SP',
      neighborhood: 'Moema',
    },
    photos: [
      'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=800&q=80',
      'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=800&q=80',
    ],
    services: ['Eventos Corporativos', 'Jantares', 'Acompanhamento'],
    pricing: {
      hour: 520,
      night: 2100,
    },
    physicalAttributes: {
      height: '1.70m',
      bodyType: 'Esbelta',
      hairColor: 'Preto',
    },
    rating: 4.9,
    reviewCount: 38,
    verified: true,
    premium: true,
    available: true,
    languages: ['Português', 'Inglês', 'Francês'],
  },
  {
    id: '7',
    name: 'Juliana',
    age: 27,
    description: 'Carismática e versátil, excelente para diversos tipos de eventos.',
    location: {
      city: 'Rio de Janeiro',
      state: 'RJ',
      neighborhood: 'Leblon',
    },
    photos: [
      'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=800&q=80',
      'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=800&q=80',
    ],
    services: ['Eventos', 'Viagens', 'Acompanhamento'],
    pricing: {
      hour: 460,
      night: 1850,
    },
    physicalAttributes: {
      height: '1.68m',
      bodyType: 'Esbelta',
      hairColor: 'Castanho',
    },
    rating: 4.8,
    reviewCount: 31,
    verified: true,
    premium: false,
    available: true,
    languages: ['Português', 'Inglês'],
  },
  {
    id: '8',
    name: 'Mariana',
    age: 25,
    description: 'Elegante e profissional, especializada em eventos sociais exclusivos.',
    location: {
      city: 'Curitiba',
      state: 'PR',
      neighborhood: 'Batel',
    },
    photos: [
      'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=800&q=80',
      'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=800&q=80',
    ],
    services: ['Eventos Sociais', 'Jantares', 'Acompanhamento'],
    pricing: {
      hour: 440,
      night: 1700,
    },
    physicalAttributes: {
      height: '1.65m',
      bodyType: 'Esbelta',
      hairColor: 'Loiro',
    },
    rating: 4.7,
    reviewCount: 22,
    verified: false,
    premium: false,
    available: true,
    languages: ['Português'],
  },
  {
    id: '9',
    name: 'Beatriz',
    age: 30,
    description: 'Experiente e refinada, perfeita para eventos de alto padrão.',
    location: {
      city: 'São Paulo',
      state: 'SP',
      neighborhood: 'Jardins',
    },
    photos: [
      'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=800&q=80',
      'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=800&q=80',
    ],
    services: ['Eventos', 'Viagens', 'Jantares'],
    pricing: {
      hour: 550,
      night: 2200,
    },
    physicalAttributes: {
      height: '1.73m',
      bodyType: 'Esbelta',
      hairColor: 'Preto',
    },
    rating: 4.9,
    reviewCount: 42,
    verified: true,
    premium: true,
    available: true,
    languages: ['Português', 'Inglês', 'Espanhol'],
  },
  {
    id: '10',
    name: 'Sereia Anderline',
    age: 35,
    description: 'Seja bem vindo, vendo conteúdos SEREIA ANDERLINE URACKH. Leia com atenção! Seja educado por favor. Não dou desconto, olhem o vídeo de comparação! Eu sou uma mulher madura de um corpo escultural, bronzeada, extrovertida, carinhosa, cheirosa e objetiva. Sou como o café, não agrado á todos. Meu programa ele inclui oral e vaginal, massagem e preliminares. Eu não faço anal, por favor não insista. Eu atendo no meu local próprio ou em motéis. O valor para ida ao motel é outro, valor de uma hora trezentos reais, meia hora cento e cinquenta. No meu encontro com você é bem tranquilo, tudo depende da nossa energia! Verifique o horário para se encontrar comigo. Aguardo você, desde já obrigada pela sua escolha farei do seu momento comigo um dos melhores sem pressa. Lembrando que eu sou uma garota de programa, não sou obrigada a atender clientes que não gostam de tomar banho! Clientes que entram no meu local fedendo, infelizmente eu não consigo agradar á todos. Higiene em primeiro lugar. Amo cliente que chega e toma banho, se liga até o xixi fede o seu pênis. Jamais vc vai chegar aqui e me pegar sem banho, e sim muito cheirosa por isso marco hora. Trabalhei seis anos em um hospital, nossa saúde é tudo. Sou uma mulher cisgênero, nasci do sexo feminino e me identifico como mulher. Minha preferência sexual é ativo-passivo, faço e recebo penetração. Tenho um corpo escultural de 1,68m de altura e 69kg, sou parda com olhos mel e cabelo loiro de tamanho médio. Não tenho silicone, mas tenho tatuagens que adoro mostrar. Não tenho piercings. Meu tamanho de pé é 37. Falo português, inglês e espanhol fluentemente. Sou uma profissional séria, discreta e que valoriza muito a higiene e o respeito. Meu atendimento é personalizado e focado em proporcionar momentos únicos e memoráveis. Trabalho com horários flexíveis e sempre priorizo o conforto e bem-estar do cliente. Venha me conhecer e viver uma experiência inesquecível!',
    location: {
      city: 'São Paulo',
      state: 'SP',
      neighborhood: 'Centro',
    },
    photos: [
      'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=800&q=80',
      'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=800&q=80',
      'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=800&q=80',
    ],
    services: ['Oral', 'Vaginal', 'Massagem', 'Preliminares', 'Atendimento em Local Próprio', 'Atendimento em Motel'],
    pricing: {
      hour: 300,
      halfHour: 150,
      night: 1200,
    },
    physicalAttributes: {
      height: '1.68m',
      weight: '69 kg',
      bodyType: 'Escultural',
      hairColor: 'Loira',
      eyeColor: 'Mel',
      ethnicity: 'Pardo',
      footSize: '37',
      hasSilicone: false,
      hasTattoos: true,
      hasPiercings: false,
      gender: 'Mulher Cisgênero',
      genitalia: 'Possui vagina',
      sexualPreference: 'Ativo - Passivo',
      hairStyle: 'Loira',
      hairSize: 'Médio',
      smoker: 'Não informado',
    },
    rating: 4.8,
    reviewCount: 67,
    verified: true,
    premium: false,
    available: true,
    languages: ['Português', 'Inglês', 'Espanhol'],
  },
]

